config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    resources :comments, only: [:index, :new]
  end
  resource :session, only: [:new, :create, :destroy]

  resources :links, only: [:new, :create, :index] do
    resources :comments, only: [:index, :new]
  end

  resources :comments, only: [:create]

  root controller: :links, action: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :link
  belongs_to :user

  validates :text, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to  :user
  has_many    :comments

  validates :url, presence: true

  def url
    if self[:url].downcase.start_with?("http")
      self[:url]
    else
      "http://" + self[:url]
    end
  end

  def url=(in_url)
    if in_url.downcase.start_with?("http")
      self[:url] = in_url
    else
      self[:url] = "http://" + in_url
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :links
  has_many :comments
  validates :name, presence: true, uniqueness: true
  validates :password_hash, presence: true

  def password
    @_password ||= BCrypt::Password.new(password_hash)
  end

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_hash = @_password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.find_by(id: session["current_user_id"])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    if params[:link_id]
      @link = Link.find(params[:link_id])
      @comments = @link.comments
    elsif params[:user_id]
      @user = User.find(params[:user_id])
      @comments = @user.comments
    else
      @user = User.find(current_user_id)
      @comments = @user.comments
    end
  end

  def show
  end

  def new
    @comment = Comment.new(link_id: params[:link_id], user_id: current_user.id, text: params[:text])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to link_comments_path(params[:comment][:link_id])
    else
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:link_id, :text)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all.order(created_at: :desc)
  end

  def new
    @link = Link.new(user_id: current_user.id)
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    if @link.save
      redirect_to links_path
    else
      render :new
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.password == params[:password]
      # Does the logging in
      session["current_user_id"] = @user.id
      redirect_to links_path
    else
      @message = "User Name Does Not Exist! Try again or Sign Up"
      render :new
    end
  end

  def destroy
    session.delete("current_user_id")
    redirect_to links_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session["current_user_id"] = @user.id
      redirect_to links_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/index.html.erb
<% if @link %>
  <h1> Comments for </h1>
  <a href=<%= @link.url %> > <%= @link.url %> </a>
  <% if current_user %>
    <p>
    <%= link_to " Add Your Comment ", new_link_comment_path(@link.id) %>
    </p>
  <% end %>
<% elsif @user %>
  <h1> Comments from <%= @user.name %> </h1>
<% end %>

<% @comments.each do |comment| %>
    <h4>
      <%= comment.id %> By:
      <%= comment.user.name %>
      <%= link_to " See More Comments ", user_comments_path(comment.user_id) %>
      <p>
        <%= comment.text %>
      </p>
    </h4>
<% end %>

app/views/comments/new.html.erb
<h1>Add a Comment!</h1>

<% @comment.errors.full_messages.each do |error|%>
  <div class="alert alert-danger">
    <%= error %>
  </div>
  <% end %>

<%= form_for @comment do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text, class: 'form-control' %>
  <%= f.hidden_field :link_id %> 
  <hr>
  <%= f.submit class: 'btn btn-primary' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgeddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <nav class='navbar navbar-default'>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <p class="navbar-text navbar-right">Signed in as <%= current_user.name %></p>
            <li><%= link_to "Log out", session_path, method: :delete %></li>
            <li><%= link_to "Add New Link", new_link_path %>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
            <li><%= link_to "Sign Up", new_user_path %></li>

          <% end %>
        </ul>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/index.html.erb
<h1>Welcome to the World of Links</h1>

<% @links.each do |link| %>
    <h4>
      <%= link.id %>:
      <a href= <%= link.url %> > <%= link.url %> </a>
      <%= link.comments.count %> comments
      <%= link_to " View Comments ", link_comments_path(link.id) %>
      <%= link_to " Add Comment ", new_link_comment_path(link.id) %>
    </h4>
<% end %>

app/views/links/new.html.erb
<h1>Add a Link!</h1>

<% @link.errors.full_messages.each do |error|%>
  <div class="alert alert-danger">
    <%= error %>
  </div>
  <% end %>

<%= form_for @link do |f| %>
  <%= f.label :url %>
  <%= f.url_field :url, class: 'form-control' %>
  <hr>
  <%= f.submit class: 'btn btn-primary' %>
  <% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% @user.errors.full_messages.each do |error| %>
  <div class="alert alert-danger">
    <%= error %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  <hr>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>